### ISSUE TITLE
MN setup script uses "emberchain.xyz" nodes

### ISSUE THREAD

**Issue by cryptonoob42** [AtheneumChain/Scripts#6]
See https://github.com/AtheneumChain/Scripts/blob/master/Masternode%20Setup/aeminstall.sh#L288

Even though they seem to resolve to the same IP addresses as the default Atheneum nodes, the relation to Ember is probably unwanted. Also, those addnode entries have no port.

They should therefore be changed to the standard nodes the Atheneum config file contains.

**Comment by AEMTech** [comment]
resolved with [e19e195](https://github.com/AtheneumChain/Scripts/commit/e19e1955705b04df38ed56f73d2fbe9af819920b)
